version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: INSERIR CREDENCIAIS
      MYSQL_DATABASE: INSERIR CREDENCIAIS
    volumes:
      - dbdata:/var/lib/mysql

  api:
    build: ./api-go
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_USER: INSERIR CREDENCIAIS
      DB_PASSWORD: INSERIR CREDENCIAIS
      DB_HOST: INSERIR CREDENCIAIS
      DB_PORT: 3306
      DB_NAME: cadastracliente

  frontend:
    build: ./frontEnd
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  dbdata:
